name: Reload databases

on:
  push:
    branches:
    - update-workflow

jobs:
  reload_api:
    name: Reload API database
    if: ${{ github.actor != 'DorpsGek' }}
    uses: TrueBrain/OpenTTD-actions/.github/workflows/rw-nomad-reload.yml@reusing-workflows
    secrets:
      RELOAD_SECRET: ${{ secrets.API_RELOAD_SECRET }}
      NOMAD_SERVICE_KEY: ${{ secrets.API_NOMAD_SERVICE_PREVIEW_KEY }}
    with:
      service: bananas-api-preview

  reload_server:
    name: Reload server database
    uses: TrueBrain/OpenTTD-actions/.github/workflows/rw-nomad-reload.yml@reusing-workflows
    secrets:
      RELOAD_SECRET: ${{ secrets.SERVER_RELOAD_SECRET }}
      NOMAD_SERVICE_KEY: ${{ secrets.SERVER_NOMAD_SERVICE_PREVIEW_KEY }}
    with:
      service: bananas-server-preview
